### ISSUE TITLE
Inaccurate requirement data for 37

### ISSUE THREAD

**Issue by denniskrq** [poooi/poi-plugin-ezexped#3]
Wiki data suggests that expedition 37 requires "at least 3 ships carrying a minimum of 4 drums" (I do believe this is true, since I have been running 37 with 3 ships on drums for as long as I can remember), but the plugin is giving me warning for "need 4 ships carrying drums"

**Comment by Javran** [comment]
Thanks for the report! the requirement is coded refering to one of my old requirement checker. at that time it was just like that. but I just checked wikiwiki and wikia, both of them have updated requirements for exped 37 confirming what you just said. since maintenance is hapenning, I'll fix this very quick and make the next release asap.
